AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template to create IAM role and policies"

Parameters:
  RoleName:
    Type: String
    Description: The name of the IAM Role
    Default: ""

Resources:
  TenableRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowTenableRoleAssumption"
            Effect: "Allow"
            Action: "sts:AssumeRole"
            Principal:
              AWS: "arn:aws:iam::081802104111:root" # Tenable's Account ID
            Condition:
              StringEquals:
                "sts:ExternalId": "9002d067-07fc-4e09-b425-59af8f47cb56" # Tenable External ID
      Policies:
        - PolicyName: "TenableReadonlyPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "acm:Describe*"
                  - "acm:List*"
                  - "aoss:BatchGet*"
                  - "aoss:List*"
                  - "autoscaling:Describe*"
                  - "batch:Describe*"
                  - "batch:List*"
                  - "bedrock:Get*"
                  - "bedrock:List*"
                  - "cloudformation:Describe*"
                  - "cloudformation:Get*"
                  - "cloudformation:List*"
                  - "cloudfront:Get*"
                  - "cloudfront:ListDistributions*"
                  - "cloudtrail:Describe*"
                  - "cloudtrail:Get*"
                  - "cloudtrail:List*"
                  - "cloudtrail:LookupEvents"
                  - "cloudwatch:Describe*"
                  - "cloudwatch:GetMetric*"
                  - "cloudwatch:ListMetrics"
                  - "cognito-idp:ListResourcesForWebACL"
                  - "cognito-sync:GetCognitoEvents"
                  - "config:Describe*"
                  - "dynamodb:Describe*"
                  - "dynamodb:List*"
                  - "ec2:Describe*"
                  - "ecr:Describe*"
                  - "ecr:GetRegistryScanningConfiguration"
                  - "ecr:GetRepositoryPolicy"
                  - "ecr:List*"
                  - "ecr:StartImageScan"
                  - "ecr-public:Describe*"
                  - "ecr-public:GetRepositoryPolicy"
                  - "ecr-public:List*"
                  - "ecs:Describe*"
                  - "ecs:List*"
                  - "eks:Describe*"
                  - "eks:List*"
                  - "elasticache:Describe*"
                  - "elasticache:List*"
                  - "elasticbeanstalk:Describe*"
                  - "elasticbeanstalk:List*"
                  - "elasticfilesystem:Describe*"
                  - "elasticloadbalancing:Describe*"
                  - "elasticmapreduce:Describe*"
                  - "elasticmapreduce:List*"
                  - "es:Describe*"
                  - "es:List*"
                  - "events:ListRules"
                  - "iam:Generate*"
                  - "iam:Get*"
                  - "iam:List*"
                  - "identitystore:Describe*"
                  - "inspector2:List*"
                  - "iot:GetTopicRule"
                  - "kms:Describe*"
                  - "kms:GetKey*"
                  - "kms:List*"
                  - "kinesis:Describe*"
                  - "kinesis:List*"
                  - "lambda:Get*Policy"
                  - "lambda:GetAccountSettings"
                  - "lambda:List*"
                  - "logs:Describe*"
                  - "organizations:Describe*"
                  - "organizations:List*"
                  - "rds:Describe*"
                  - "rds:List*"
                  - "redshift:Describe*"
                  - "redshift:List*"
                  - "route53:List*"
                  - "s3:Get*"
                  - "s3:List*"
                  - "secretsmanager:Describe*"
                  - "secretsmanager:Get*"
                  - "secretsmanager:List*"
                  - "securityhub:Batch*"
                  - "securityhub:Get*"
                  - "securityhub:List*"
                  - "servicecatalog:List*"
                  - "sns:List*"
                  - "sqs:List*"
                  - "ssm:Describe*"
                  - "ssm:Get*"
                  - "ssm:List*"
                  - "states:List*"
                  - "support:Describe*"
                  - "tag:Get*"
                  - "transfer:List*"
                  - "waf-regional:List*"
                  - "waf:List*"
                  - "workmail:Describe*"
                  - "workmail:List*"
                Resource: "*"

        - PolicyName: "TenableDataScanningPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "dynamodb:Scan"
                  - "kms:CreateGrant"
                  - "kms:Decrypt"
                  - "kms:Encrypt"
                  - "kms:GenerateDataKeyWithoutPlaintext"
                  - "kms:ReEncryptFrom"
                  - "kms:ReEncryptTo"
                  - "rds:CopyDBClusterSnapshot"
                  - "rds:CopyDBSnapshot"
                  - "rds:CreateDBClusterSnapshot"
                  - "rds:CreateDBSnapshot"
                  - "rds:ModifyDBClusterSnapshotAttribute"
                  - "rds:ModifyDBSnapshotAttribute"
                  - "s3:GetObject"
                  - "s3:ListBucket"
                Resource: "*"
        

Outputs:
  RoleName:
    Value: !Ref TenableRole